'use client';
import { useState } from 'react';
import Image from 'next/image';
import { Wallet, Gift, Trophy, Disc3, BookOpen, ArrowRight, ChevronRight, Home, User, Check, ArrowUpRight } from 'lucide-react';
import { Count } from './motion';
const features=[{title:'Uma carteira de conquistas',label:'Carteira',icon:Wallet,text:'Cada reconhecimento fica aqui. O colaborador acompanha seu saldo, suas conquistas e pode transferir coins para colegas da mesma empresa.'},{title:'Coins que viram vida real',label:'Benefícios',icon:Gift,text:'Um jantar, uma nova leitura, um cuidado a mais. O time escolhe como aproveitar suas coins nos estabelecimentos parceiros.'},{title:'Uma dose de competição saudável',label:'Ranking',icon:Trophy,text:'Um ranking mensal para acompanhar conquistas e celebrar quem está fazendo acontecer junto com o time.'},{title:'A próxima surpresa está no giro',label:'Roleta',icon:Disc3,text:'A roleta de prêmios transforma os giros disponíveis no app em mais um momento de descoberta e recompensa.'},{title:'Aprender também é conquistar',label:'Cursos',icon:BookOpen,text:'O desenvolvimento faz parte da jornada. Seu time conclui cursos, aprende novas habilidades e ganha coins.'}];
function Screen({active}:{active:number}) {
 if(active===0) return <div className="real-screen"><Image src="/images/app-wallet.jpeg" alt="Tela real do app mrcoin com saldo, recompensas, ranking e cursos" width={434} height={1280} sizes="300px"/></div>;
 return <div className="mock-screen"><div className="mock-welcome">Seu universo de coins <span>R</span></div><h4>{features[active].label}</h4>{active===1&&<><div className="mini-balance">SEU SALDO <strong>39.950 <small>coins</small></strong></div><p className="mock-subtitle">Escolha sua próxima recompensa</p>{[{emoji:'☕',name:'Uma pausa para você',type:'Cafeteria',coins:'250'},{emoji:'📖',name:'Sua próxima boa história',type:'Livraria',coins:'800'},{emoji:'🍝',name:'Sabores para compartilhar',type:'Restaurante',coins:'1.200'}].map(i=><div className="reward" key={i.name}><span className="reward-art">{i.emoji}</span><div><small>{i.type}</small><b>{i.name}</b><em>{i.coins} coins <ArrowUpRight size={12}/></em></div></div>)}</>}{active===2&&<><div className="ranking-title"><Trophy size={34}/><h5>Todo esforço conta.</h5><span>Ranking do mês</span></div><div className="podium"><div><span>LC</span><b>Lucas</b><small>2º lugar</small></div><div><span className="winner">AM</span><b>Ana</b><small>1º lugar</small></div><div><span>JS</span><b>Julia</b><small>3º lugar</small></div></div>{['Ana Martins','Lucas Costa','Julia Santos','Você'].map((n,i)=><div className={i===3?'rank-row you':'rank-row'} key={n}><span>0{i+1}</span><b>{n}</b><small>{4200-i*450} coins</small></div>)}</>}{active===3&&<><div className="ranking-title"><h5>Sua sorte pode virar coins.</h5><span>Você tem 3 giros disponíveis</span></div><div className="wheel"><span>500</span><span>100</span><span>250</span><span>50</span><b>MR.</b></div><div className="mock-yellow">Uma nova surpresa a cada giro</div><p className="mock-subtitle centered">As recompensas fazem parte<br/>da experiência no app.</p></>}{active===4&&<><div className="mini-balance">SUA JORNADA <strong>Aprenda. Evolua. Ganhe.</strong></div><div className="course-art"><BookOpen size={48}/><span>DESENVOLVIMENTO</span></div><div className="course-card"><small>EM ANDAMENTO</small><h5>Hospitalidade</h5><p>Pequenos gestos, grandes experiências.</p><div className="progress"><span/></div><div className="course-meta"><span>Seu próximo passo</span><b>+500 coins</b></div></div><div className="reward compact"><Check size={22}/><div><b>Conhecimento reconhecido</b><small>Conclua cursos e receba coins.</small></div></div></> }<div className="mock-bottom"><Home/><Gift/><BookOpen/><Wallet/><User/></div></div>;
}
export default function Showcase(){const [active,setActive]=useState(0);return <div className="showcase-grid"><div className="feature-list" role="tablist" aria-label="Recursos do app" aria-orientation="vertical">{features.map((f,i)=><button key={f.label} role="tab" aria-selected={active===i} aria-controls="app-panel" id={`feature-${i}`} tabIndex={active===i?0:-1} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowDown'?1:4))%5;setActive(next);document.getElementById(`feature-${next}`)?.focus();}}} className={active===i?'feature active':'feature'} onClick={()=>setActive(i)}><span className="feature-icon"><f.icon size={21}/></span><span><b>{f.label}</b>{active===i&&<span className="feature-description">{f.text}</span>}</span><ChevronRight size={17}/></button>)}</div><div className="phone-stage" id="app-panel" role="tabpanel" aria-labelledby={`feature-${active}`}><div className="phone"><div className="phone-camera"/><Screen active={active}/></div><div className="floating-reward"><span className="round-icon"><Check size={18}/></span><div><small>Aprendizado reconhecido</small><b>+<Count value={500}/> coins <span>✦</span></b></div></div><p className="screen-caption">{active===0?'Tela real do app mrcoin':'Interface ilustrativa · valores demonstrativos'}</p></div><div className="showcase-aside"><span className="eyebrow">DO RECONHECIMENTO À CONQUISTA</span><h3>{features[active].title}</h3><p>Um app que coloca o valor de fazer parte na palma da mão.</p><a href="#contato" className="text-link">Quero essa experiência no meu time <ArrowRight size={17}/></a></div></div>}
